name: Progressive release

on:
  workflow_dispatch:
    inputs:
      env:  
        description: 'Environment'
        required: true
        default: 'production' # qa | prod
jobs:
  release_through_circle_ci:
    runs-on: ubuntu-latest
    name: Progressive deploy EB-UI application through Circle CI
    steps:
      - name: Opening 5% traffic
        run: echo "Opening 5% traffic"
      - name: Wait for 5 minutes
        run: sleep 5m
        shell: bash
      - name: Opening 10% traffic
        run: echo "Opening 10% traffic"
      - name: Wait for 5 minutes
        run: sleep 5m
        shell: bash
      - name: Opening 25% traffic
        run: echo "Opening 25% traffic"
      - name: Wait for 5 minutes
        run: sleep 5m
        shell: bash
      - name: Opening 100% traffic
        run: echo "Opening 100% traffic"